### ISSUE TITLE
[EditorConfig] Unrecognized values in charset property throw exceptions.

### ISSUE THREAD

**Issue by EricDunsworth** [schorfES/node-lintspaces#48]
Lintspaces doesn't claim to support .editorconfig's ``charset`` property, but appears to be reading it and attempting to use it in a way that can lead to exceptions.

An exception can occur if the ``charset`` property's value is unrecognized. Out of [EditorConfig's 5 supported charsets](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#charset), lintspaces seems to understand ``latin1``, ``utf-8`` and ``utf-16le``, but errors out with ``utf-16be`` and ``utf-8-bom``.

The same is also true for ``unset``/invalid values. Btw I didn't cover the ``charset`` property in #47 since its exception would've prevented other warnings from appearing.

Would it be possible to either completely ignore the ``charset`` property or improve lintspace's handling of it?

**Code/Output samples...**
The samples below demonstrates how lintspaces currently reacts to a ``charset = utf-8-bom`` property.

**.editorconfig**

```editorconfig
root = true

[*]
charset = utf-8-bom
```

**test.txt** (BOM's presence doesn't matter)
```txt
test
```

**check.js**
```js
var Validator = require('lintspaces');

var validator = new Validator({editorconfig: '.editorconfig'});
validator.validate('test.txt');

//Derived from https://stackoverflow.com/a/10729284
var results = validator.getInvalidFiles();

const util = require('util');

console.log(util.inspect(results, {showHidden: false, depth: null}));
```

**Output when running ``node check.js`` in Windows:**
```js
internal/fs.js:21
    throw new Error(`Unknown encoding: ${encoding}`);
    ^

Error: Unknown encoding: utf-8-bom
    at assertEncoding (internal/fs.js:21:11)
    at getOptions (fs.js:80:5)
    at Object.fs.readFileSync (fs.js:549:13)
    at Validator._loadFile (C:\lintspaces-testing\node_modules\lintspaces\lib\Validator.js:123:18)
    at Validator.validate (C:\lintspaces-testing\node_modules\lintspaces\lib\Validator.js:66:8)
    at Object.<anonymous> (C:\lintspaces-testing\check.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Expected output of ``node check.js``:**
```js
{}
```

**Comment by schorfES** [comment]
Hi @EricDunsworth,
thank you for this detailed issue. This seems to be related to a unsupported encoding setting which is passed from editorconfig to [readFileSync](https://github.com/schorfES/node-lintspaces/blob/master/lib/Validator.js#L123). I think lintspaces needs to check if the received encoding is a supported value for node's readFileSync(). I'm not clear about what will happen when lintspaces provides a fallback (`utf-8-bom` to `utf-8`) if the encoding isn't supported.
I need to dive a bit deeper into it and will fix this problem in a future release. However, if you need a faster fix, I would be very happy to accept a PR to solve this.

**Comment by Bartheleway** [comment]
It seems [Node](https://github.com/nodejs/node/blob/main/lib/buffer.js#L631) itself doesn't support the "BOM" version of encodings.

Also looking at the code, it seems that this package try to read the file with the given encoding without trying to verify that the file is in this encoding. This could be achieve with [ced](https://github.com/sonicdoe/ced) for example. It use some C++ locally compiled source which feels bad when trying to reduce the number of dependencies to install (require node-gyp which requires some C++ compiler).

I assume having a fallback to make all the other checks is good as "BOM" flag doesn't change meaning of EOL, spaces, ending line.

According to editorconfig website, it supports : latin1, utf-8, utf-8-bom, utf-16be and utf-16le
And Node seems to support : latin1, utf-8 and utf-16le

I am really not an expert of encoding. It seems safe to fallback from utf-8-bom to utf-8 and from utf-16be to utf-16le. What do you think ?

**Comment by schorfES** [comment]
We could consider using [chardet](https://www.npmjs.com/package/chardet) instead. This library has no dependencies and does not require native code or bindings (see here https://www.npmjs.com/package/chardet#chardet). However, @Bartheleway makes a good point that we might need to either narrow down the list of supported encodings or attempt to open the file based on the encoding setting. Here’s an example approach:

```js
const chardet = require('chardet');
const fs = require('fs');

// Path to the file you want to check
const filePath = 'path/to/your/file.txt';

// List of supported encodings
const supportedEncodings = ['latin1', 'utf-8', 'utf-16le'];

// Detect the file encoding
const encoding = chardet.detectFileSync(filePath);

// Check if the file encoding is supported
if (!supportedEncodings.includes(encoding)) {
  throw new Error('Unsupported encoding');
}

// Warn if the encoding does not match the settings
if (typeof validator.settings.encoding === 'string' && validator.settings.encoding !== encoding) {
  console.warn('Encoding mismatch: setting does not match file encoding');
}

// Read the file with the detected encoding
fs.readFileSync(filePath, encoding);
```

**Comment by Bartheleway** [comment]
I looked into `chardet` and it doesn't seems to detect BOM ... also I think we should `report` encoding error like package is doing for lines but I didn't find how to add an error to the whole file.

**Comment by Bartheleway** [comment]
Maybe we can use [jschardet](https://www.npmjs.com/package/jschardet)

**Comment by EricDunsworth** [comment]
@schorfES Would there potentially be value in making lintspaces completely ignore EditorConfig's ``charset`` property until this issue is resolved?

I recently noticed that ``charset = unset`` is still throwing the following exception in node.js v24.x in the [latest commit](https://github.com/schorfES/node-lintspaces/commit/b5ed5d994ea1d3be64de837d61c8f3533046836a):
```
node:internal/fs/utils:327
    throw new ERR_INVALID_ARG_TYPE('options', ['string', 'Object'], options);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be one of type string or object. Received type boolean (false)
    at getOptions (node:internal/fs/utils:327:11)
    at Object.readFileSync (node:fs:434:13)
    at Validator._loadFile (C:\git\node-lintspaces\src\Validator.js:162:19)
    at Validator.validate (C:\git\node-lintspaces\src\Validator.js:80:9)
    at Object.<anonymous> (C:\git\node-lintspaces\check.js:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1812:14)
    at Object..js (node:internal/modules/cjs/loader:1943:10)
    at Module.load (node:internal/modules/cjs/loader:1533:32)
    at Module._load (node:internal/modules/cjs/loader:1335:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Which makes sense in the context of this issue (undocumented partial support for ``charset`` and exceptions when encountering unrecognized values).

But it kind of clashes with the "spirit" behind #47 (which focused specifically on handling the ``unset`` value) and [0.12.0's release notes](https://github.com/schorfES/node-lintspaces/releases/tag/0.12.0) (which claimed that lintspaces could now handle "unset" and invalid EditorConfig values - implying full support by all properties).

**PS:**
I could open a separate issue for this if needed. But it looks like I had already alluded to it in this issue's OP :P.

Btw I deliberately excluded ``charset`` from #47's example to prevent it from inducing an exception (since I felt like the exception would get in the way of what I was trying to demonstrate in the example).

**Comment by schorfES** [comment]
Hi @EricDunsworth, could you please share a few examples that we can use to create test cases? That would help start implementing the fix and handling the scenarios you've described. I would be happy if you could start a PR.

**Comment by schorfES** [comment]
Maybe setting `unset: true` already solves the issue. The `EditorConfig` documentation states:

> **unset**
> _If true, after combining all properties, remove all properties whose value remains as "unset"._

If that's the case, we might not need any additional handling and could simply rely on EditorConfig's built-in behavior.
